-- Migration number: 0NaN 	 2025-03-18T18:21:27.079Z
DROP TABLE IF EXISTS Tasks;
CREATE TABLE IF NOT EXISTS Tasks (id TEXT PRIMARY KEY, status TEXT, request TEXT, serverId TEXT, result TEXT, createdAt INTEGER DEFAULT CURRENT_TIMESTAMP, updatedAt INTEGER DEFAULT CURRENT_TIMESTAMP);